In [1]:
from time import perf_counter

import pandas as pd
import numpy as np
import plotly.express as px

pd.options.plotting.backend = "plotly"

df = pd.read_csv("shapes.csv")
df.head()

,shape,pixel_0_0,pixel_0_1,pixel_0_2,pixel_0_3,pixel_0_4,pixel_0_5,pixel_0_6,pixel_0_7,pixel_0_8,...,pixel_27_18,pixel_27_19,pixel_27_20,pixel_27_21,pixel_27_22,pixel_27_23,pixel_27_24,pixel_27_25,pixel_27_26,pixel_27_27
0,circles,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1,circles,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2,circles,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
3,circles,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
4,circles,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0


In [2]:
df["shape"].value_counts()

shape
circles      200
squares      200
triangles    200
Name: count, dtype: int64

In [3]:
df.iloc[204]

shape          squares
pixel_0_0          1.0
pixel_0_1          1.0
pixel_0_2          1.0
pixel_0_3          1.0
                ...   
pixel_27_23        1.0
pixel_27_24        1.0
pixel_27_25        1.0
pixel_27_26        1.0
pixel_27_27        1.0
Name: 204, Length: 785, dtype: object

In [4]:
df.iloc[204, 1:].to_numpy().reshape(28, 28)

array([[np.float64(1.0), np.float64(1.0), np.float64(1.0),
        np.float64(1.0), np.float64(1.0), np.float64(1.0),
        np.float64(1.0), np.float64(1.0), np.float64(1.0),
        np.float64(1.0), np.float64(1.0), np.float64(1.0),
        np.float64(1.0), np.float64(1.0), np.float64(1.0),
        np.float64(1.0), np.float64(1.0), np.float64(1.0),
        np.float64(1.0), np.float64(1.0), np.float64(1.0),
        np.float64(1.0), np.float64(1.0), np.float64(1.0),
        np.float64(1.0), np.float64(1.0), np.float64(1.0),
        np.float64(1.0)],
       [np.float64(1.0), np.float64(1.0), np.float64(1.0),
        np.float64(1.0), np.float64(1.0), np.float64(1.0),
        np.float64(1.0), np.float64(1.0), np.float64(1.0),
        np.float64(1.0), np.float64(1.0), np.float64(1.0),
        np.float64(1.0), np.float64(1.0), np.float64(1.0),
        np.float64(1.0), np.float64(1.0), np.float64(1.0),
        np.float64(1.0), np.float64(1.0), np.float64(1.0),
        np.float64(1.0), np.fl

In [5]:
px.imshow(df.iloc[204, 1:].to_numpy().reshape(28, 28), color_continuous_scale="gray")

In [6]:
df["shape"].isin(["circles", "squares"])

0       True
1       True
2       True
3       True
4       True
       ...  
595    False
596    False
597    False
598    False
599    False
Name: shape, Length: 600, dtype: bool

In [7]:
df_bin = df[df["shape"].isin(["circles", "squares"])]
df_bin["shape"].value_counts()

shape
circles    200
squares    200
Name: count, dtype: int64

In [8]:
X = df_bin.drop(columns=["shape"])
y = df_bin["shape"].eq("circles").astype(int)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

y_train.value_counts(), y_test.value_counts(),

(shape
 1    160
 0    160
 Name: count, dtype: int64,
 shape
 0    40
 1    40
 Name: count, dtype: int64)

In [9]:
w = np.zeros(28 * 28)
w

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [10]:
X_train.iloc[0].to_numpy() @ np.ones(28 * 28)

np.float64(731.3098084926605)

In [11]:
from numpy.typing import NDArray

class Perceptron:
    w: NDArray
    b: float
    lr: float

    def __init__(self, learning_rate: float):
        self.w = np.zeros(28 * 28)
        self.b = 0.0
        self.lr = learning_rate

    def forward(self, x_i: NDArray) -> int:
        act = self.w @ x_i + self.b
        return 1 if act > 0 else 0

    def update(self, x_i: NDArray, y_i: int) -> None:
        y_i_hat = self.forward(x_i)
        self.w += self.lr * (y_i - y_i_hat) * x_i

In [12]:
perceptron = Perceptron(0.05)
perceptron

In [13]:
perceptron.forward(X_train.iloc[0].to_numpy())

0

In [14]:
perceptron.w

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [15]:
perceptron.update(X_train.iloc[0].to_numpy(), y_train.iloc[0])

In [16]:
perceptron.w

array([0.05      , 0.05      , 0.05      , 0.05      , 0.05      ,
       0.05      , 0.05      , 0.05      , 0.05      , 0.05      ,
       0.05      , 0.05      , 0.05      , 0.05      , 0.05      ,
       0.05      , 0.05      , 0.04960784, 0.05      , 0.05      ,
       0.05      , 0.05      , 0.05      , 0.05      , 0.05      ,
       0.05      , 0.05      , 0.05      , 0.05      , 0.05      ,
       0.05      , 0.05      , 0.05      , 0.05      , 0.05      ,
       0.05      , 0.05      , 0.05      , 0.05      , 0.05      ,
       0.05      , 0.04921569, 0.04313726, 0.0354902 , 0.03313726,
       0.03470588, 0.04745098, 0.05      , 0.05      , 0.05      ,
       0.05      , 0.05      , 0.05      , 0.05      , 0.05      ,
       0.05      , 0.05      , 0.05      , 0.05      , 0.05      ,
       0.05      , 0.05      , 0.05      , 0.05      , 0.05      ,
       0.05      , 0.05      , 0.05      , 0.04647059, 0.02686275,
       0.02098039, 0.02411765, 0.00941177, 0.01705882, 0.04450

In [17]:
perceptron = Perceptron(0.05)

In [18]:
def train_loss_perceptron(p: Perceptron) -> float:
    loss = 0.0
    n = X_train.shape[0]
    for i in range(n):
        x_i = X_train.iloc[i].to_numpy()
        y_i = y_train.iloc[i]
        y_i_hat = p.forward(x_i)
        loss += np.abs(y_i - y_i_hat)
    return loss / n

def test_loss_perceptron(p: Perceptron) -> float:
    loss = 0.0
    n = X_test.shape[0]
    for i in range(n):
        x_i = X_test.iloc[i].to_numpy()
        y_i = y_test.iloc[i]
        y_i_hat = p.forward(x_i)
        loss += np.abs(y_i - y_i_hat)
    return loss / n

In [19]:
train_loss_perceptron(perceptron)

np.float64(0.5)

In [42]:
def train_perceptron(p: Perceptron, max_epochs: int, stop_under = 0.001) -> pd.DataFrame:
    metrics = []
    n = X_train.shape[0]

    for epoch in range(max_epochs):
        for i in range(n):
            x_i = X_train.iloc[i].to_numpy()
            y_i = y_train.iloc[i]
            p.update(x_i, y_i)

        train_loss = train_loss_perceptron(p)
        test_loss = test_loss_perceptron(p)
        metrics.append([epoch, train_loss, test_loss])
        print(f"End of epoch {epoch}: Train loss {train_loss:.3f}, Test loss {test_loss:.3f}")
        if train_loss < stop_under:
            print(f"Train loss {train_loss:.3f} < {stop_under:.3f}, stopping. Test loss {test_loss:.3f}")
            break

    return pd.DataFrame(metrics, columns=["epoch", "train_loss", "test_loss"]).set_index("epoch")

In [43]:
perceptron = Perceptron(0.001)
metrics = train_perceptron(perceptron, 500)

End of epoch 0: Train loss 0.500, Test loss 0.500
End of epoch 1: Train loss 0.500, Test loss 0.500
End of epoch 2: Train loss 0.500, Test loss 0.500
End of epoch 3: Train loss 0.500, Test loss 0.500
End of epoch 4: Train loss 0.500, Test loss 0.500
End of epoch 5: Train loss 0.500, Test loss 0.500
End of epoch 6: Train loss 0.500, Test loss 0.500
End of epoch 7: Train loss 0.500, Test loss 0.500
End of epoch 8: Train loss 0.500, Test loss 0.500
End of epoch 9: Train loss 0.500, Test loss 0.500
End of epoch 10: Train loss 0.500, Test loss 0.500
End of epoch 11: Train loss 0.500, Test loss 0.500
End of epoch 12: Train loss 0.500, Test loss 0.500
End of epoch 13: Train loss 0.500, Test loss 0.500
End of epoch 14: Train loss 0.500, Test loss 0.500
End of epoch 15: Train loss 0.500, Test loss 0.500
End of epoch 16: Train loss 0.500, Test loss 0.500
End of epoch 17: Train loss 0.500, Test loss 0.500
End of epoch 18: Train loss 0.500, Test loss 0.500
End of epoch 19: Train loss 0.144, Test l

In [44]:
metrics.plot()

In [49]:
perceptron2 = Perceptron(0.001)
perceptron2.w = np.random.uniform(0, 1, size=(28 * 28))
perceptron2.b = np.random.uniform(0, 1)
perceptron2.w, perceptron2.b

(array([0.46749152, 0.77609662, 0.99344796, 0.12100334, 0.0512327 ,
        0.04378069, 0.53653175, 0.02843523, 0.24599149, 0.51535386,
        0.97580496, 0.51435128, 0.43808518, 0.99693602, 0.84836688,
        0.07460016, 0.50473162, 0.04016818, 0.95203253, 0.38462253,
        0.23839439, 0.90910244, 0.24534131, 0.08014179, 0.25398945,
        0.87408629, 0.45529147, 0.25529104, 0.31713296, 0.35041067,
        0.17354998, 0.2681271 , 0.97081787, 0.61401586, 0.76084104,
        0.22333982, 0.72704548, 0.34519609, 0.02956512, 0.23650312,
        0.85210561, 0.12896345, 0.23218698, 0.30276139, 0.40078493,
        0.34045685, 0.55286426, 0.44424515, 0.1661916 , 0.88379172,
        0.18182246, 0.46018791, 0.71145142, 0.96777586, 0.86706525,
        0.68542586, 0.99814327, 0.14893841, 0.54850808, 0.22382697,
        0.09512159, 0.95290763, 0.24935876, 0.40689381, 0.03506171,
        0.89405733, 0.6480608 , 0.81238114, 0.83532431, 0.86436721,
        0.33952465, 0.97754849, 0.2143212 , 0.78

In [50]:
metrics = train_perceptron(perceptron2, 1000)
metrics.plot()

End of epoch 0: Train loss 0.500, Test loss 0.500
End of epoch 1: Train loss 0.500, Test loss 0.500
End of epoch 2: Train loss 0.500, Test loss 0.500
End of epoch 3: Train loss 0.478, Test loss 0.438
End of epoch 4: Train loss 0.506, Test loss 0.500
End of epoch 5: Train loss 0.447, Test loss 0.487
End of epoch 6: Train loss 0.431, Test loss 0.450
End of epoch 7: Train loss 0.422, Test loss 0.463
End of epoch 8: Train loss 0.484, Test loss 0.487
End of epoch 9: Train loss 0.463, Test loss 0.475
End of epoch 10: Train loss 0.456, Test loss 0.475
End of epoch 11: Train loss 0.431, Test loss 0.475
End of epoch 12: Train loss 0.422, Test loss 0.438
End of epoch 13: Train loss 0.428, Test loss 0.438
End of epoch 14: Train loss 0.397, Test loss 0.412
End of epoch 15: Train loss 0.403, Test loss 0.388
End of epoch 16: Train loss 0.397, Test loss 0.412
End of epoch 17: Train loss 0.384, Test loss 0.438
End of epoch 18: Train loss 0.353, Test loss 0.438
End of epoch 19: Train loss 0.397, Test l

In [34]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train, y_train)

,"n_neighbors n_neighbors: int, default=5Number of neighbors to use by default for :meth:`kneighbors` queries.",5
,"weights weights: {'uniform', 'distance'}, callable or None, default='uniform'Weight function used in prediction. Possible values:- 'uniform' : uniform weights. All points in each neighborhood are weighted equally.- 'distance' : weight points by the inverse of their distance. in this case, closer neighbors of a query point will have a greater influence than neighbors which are further away.- [callable] : a user-defined function which accepts an array of distances, and returns an array of the same shape containing the weights.Refer to the example entitled:ref:`sphx_glr_auto_examples_neighbors_plot_classification.py`showing the impact of the `weights` parameter on the decisionboundary.",'uniform'
,"algorithm algorithm: {'auto', 'ball_tree', 'kd_tree', 'brute'}, default='auto'Algorithm used to compute the nearest neighbors:- 'ball_tree' will use :class:`BallTree`- 'kd_tree' will use :class:`KDTree`- 'brute' will use a brute-force search.- 'auto' will attempt to decide the most appropriate algorithm based on the values passed to :meth:`fit` method.Note: fitting on sparse input will override the setting ofthis parameter, using brute force.",'auto'
,"leaf_size leaf_size: int, default=30Leaf size passed to BallTree or KDTree. This can affect thespeed of the construction and query, as well as the memoryrequired to store the tree. The optimal value depends on thenature of the problem.",30
,"p p: float, default=2Power parameter for the Minkowski metric. When p = 1, this is equivalentto using manhattan_distance (l1), and euclidean_distance (l2) for p = 2.For arbitrary p, minkowski_distance (l_p) is used. This parameter is expectedto be positive.",2
,"metric metric: str or callable, default='minkowski'Metric to use for distance computation. Default is ""minkowski"", whichresults in the standard Euclidean distance when p = 2. See thedocumentation of `scipy.spatial.distance`_ andthe metrics listed in:class:`~sklearn.metrics.pairwise.distance_metrics` for valid metricvalues.If metric is ""precomputed"", X is assumed to be a distance matrix andmust be square during fit. X may be a :term:`sparse graph`, in whichcase only ""nonzero"" elements may be considered neighbors.If metric is a callable function, it takes two arrays representing 1Dvectors as inputs and must return one value indicating the distancebetween those vectors. This works for Scipy's metrics, but is lessefficient than passing the metric name as a string.",'minkowski'
,"metric_params metric_params: dict, default=NoneAdditional keyword arguments for the metric function.",None
,"n_jobs n_jobs: int, default=NoneThe number of parallel jobs to run for neighbors search.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary `for more details.Doesn't affect :meth:`fit` method.",None


In [36]:
1 - knn.score(X_test, y_test)

0.1875